//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOPORTE.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Recursos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recursos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SOPORTE.Recursos.Recursos", typeof(Recursos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spActualizarPersona.
        /// </summary>
        public static string actualizarPersona {
            get {
                return ResourceManager.GetString("actualizarPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spConsultarPersonas.
        /// </summary>
        public static string consultarPersonas {
            get {
                return ResourceManager.GetString("consultarPersonas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spConsultarPersonasIdentificador.
        /// </summary>
        public static string consultarPersonasId {
            get {
                return ResourceManager.GetString("consultarPersonasId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spConsultarUsuario.
        /// </summary>
        public static string consultarUsuario {
            get {
                return ResourceManager.GetString("consultarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.spCrearPersona.
        /// </summary>
        public static string crearPersona {
            get {
                return ResourceManager.GetString("crearPersona", resourceCulture);
            }
        }
    }
}
